export enum MissedReasonType {
  FORGOT = "FORGOT",
  HARD_TO_START = "HARD_TO_START",
  TOO_BIG = "TOO_BIG",
  EMOTIONALLY_HEAVY = "EMOTIONALLY_HEAVY",
  TIME_MISMATCH = "TIME_MISMATCH",
  JUST_SKIP = "JUST_SKIP",
}
